--CREATE ROLE fred LOGIN
 -- ENCRYPTED PASSWORD 'md52697359d57024a8f41301b0332a8ba39'
--  SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;


-- Sequence: musicmanager_id_seq
 CREATE SEQUENCE musicmanager_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

ALTER TABLE musicmanager_id_seq
 OWNER TO docker;

--CREATE ROLE group_fred
--  SUPERUSER INHERIT NOCREATEDB NOCREATEROLE REPLICATION;

--ALTER DEFAULT PRIVILEGES
--    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
--    TO group_fred;

--ALTER DEFAULT PRIVILEGES
--    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
--    TO group_fred;
