CREATE ROLE fred LOGIN
  ENCRYPTED PASSWORD 'md52697359d57024a8f41301b0332a8ba39'
  SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;

ALTER TABLE musicmanager_id_seq
  OWNER TO fred;

CREATE ROLE group_fred
  SUPERUSER INHERIT NOCREATEDB NOCREATEROLE REPLICATION;

ALTER DEFAULT PRIVILEGES
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO group_fred;

CREATE DATABASE musicmanager
  WITH OWNER = fred
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'fr_FR.UTF-8'
       LC_CTYPE = 'fr_FR.UTF-8'
       CONNECTION LIMIT = -1;

ALTER DEFAULT PRIVILEGES
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO group_fred;